import images from './images';

const coursesData = [
  {
    name: 'Introduction to user research in UX Design',
    category: 'Design',
    author: 'Leonard Victor',
    thumbnail: images.course1,
    price: '15.00',
    duration: '23hrs 50mins',
    lessons: 15,
    ratings: 4.7,
    numberReviewed: '32.7k+',
  },
  {
    name: 'introduction to  new marketing audience ',
    category: 'Marketing',
    author: 'Jeffrey Williams',
    thumbnail: images.course2,
    price: '32.00',
    duration: '22hrs 30mins',
    lessons: 22,
    ratings: 4.7,
    numberReviewed: '8.7k+',
  },
  {
    name: 'introduction to html, css & bootstrap',
    category: 'Development',
    author: 'claretta mason',
    thumbnail: images.course3,
    price: '55.00',
    duration: '45hrs 50mins',
    lessons: 15,
    ratings: 4.7,
    numberReviewed: '12.7k+',
  },
  {
    name: 'introduction to javascript, git & GitHub',
    category: 'Development',
    author: 'Jessica Duke',
    thumbnail: images.course4,
    price: '45.00',
    duration: '30hrs 50mins',
    lessons: 22,
    ratings: 4.7,
    numberReviewed: '32.7k+',
  },
  {
    name: 'introduction to outroom  marketing analysis',
    category: 'Marketing',
    author: 'Samuel jacobs',
    thumbnail: images.course5,
    price: '25.00',
    duration: '33hrs 50mins',
    lessons: 26,
    ratings: 4.7,
    numberReviewed: '4.7k+',
  },
  {
    name: 'introduction to live  marketing analysis',
    category: 'Marketing',
    author: 'adam smith',
    thumbnail: images.course6,
    price: '25.00',
    duration: '10hrs 50mins',
    lessons: 32,
    ratings: 4.7,
    numberReviewed: '15.7k+',
  },
];

export default coursesData;
